import type { Metadata } from "next";
import { roboto400 } from './fonts';
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`h-screen bg-gradient-to-b from-primary-700 from-10% to-dark-200 ${roboto400.className} overflow-hidden`}>
        <Navbar />
        <div className="pb-16 sm:ml-16">
          {children}
        </div>
      </body>
    </html>
  );
}
